#define STATUS_OK 1	//状态码:OK
#define STATUS_NO_BLOCK -1	//状态码:无空闲盘块
#define STATUS_NO_INODE -2	//状态码:无空闲iNode
#define STATUS_BEYOND_DIRECT_NUM -3	//状态码:超出当前目录最大文件或目录数
#define STATUS_READ_ONLY -4		//状态码:只读
#define STATUS_ERROR -5		//状态码:错误
#define STATUS_FILE_OPEN_ERROR -6 //状态吗:文件打开失败
#define STATUS_FILENAME_EXIST	-7	//状态码:文件名或目录名存在
#define STATUS_FILENAME_NONEXIST -8	//状态码:文件名或目录名不存在
#define STATUS_BEYOND_RIGHT -9	//状态码:超越权限
#define STATUS_MOD_ERROR -10	//状态码:Mod码错误
#define STATUS_OWNER_NONEXIST -11	//状态码:用户Id不存在
#define STATUS_GROUP_NONEXIST -12	//状态码:用户组不存在
#define STATUS_PASSWORD_WRONG -13	//状态码:密码错误
#define STATUS_CONFIRM_WRONG -14	//状态码:确认密码错误
#define STATUS_NOT_FILE	-15			//状态码:不是一个文件
#define STATUS_BEYOND_SIZE -16		//超出最大限度
#define STATUS_WRITE_ONLY -17		//状态码:只写
#define STATUS_NOT_DIRECT -18		//状态码:不是一个目录
#define STATUS_TYPE_NOT_MATCH -19	//状态码:类型不一致
#define STATUS_SDNAME_OVERLAP -20		//状态码:源文件名字和目标文件名字重叠